package utils

import (
	"context"

	"github.com/jackc/pgx/v4/pgxpool"
)

const (
	CREATE_TABLE_USERS string = `CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		email TEXT NOT NULL UNIQUE,
		username TEXT NOT NULL UNIQUE,
		password TEXT NOT NULL
	)`
)

func ConnectToDB(ctx context.Context, connectionURL string) (*pgxpool.Pool, error) {
	return pgxpool.Connect(ctx, connectionURL)
}

func MigrateTable(ctx context.Context, conn *pgxpool.Pool) error {
	_, err := conn.Exec(ctx, CREATE_TABLE_USERS)
	return err
}
